"""Portable byte snapshots of unchanged v1 APIs, captured against signed main.

The helper is deliberately limited to the two pre-existing APIs. Its fake
decoder gives fixed native RGB/timing while the real v1 image writer produces
PNG bytes. Only temporary absolute source path spellings and library-version
labels are normalized; every other serialized field, image length and digest
is retained. The baseline hashes in the test were generated by running this
helper with source from signed main 211e611b7535d46308e8ff000d5caa71a10e8082.
"""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path
from types import SimpleNamespace
from typing import Any


def capture_v1_wire(root: Path) -> dict[str, bytes]:
    import frame_quorum.native_scene_images as images
    import frame_quorum.native_video as native
    from frame_quorum import NativeConcatClip, detect_native_concat_scenes, export_native_scene_images
    from tests.test_native_video import FakeContainer, FakeFrame

    first, second = root / "a.mkv", root / "b.mkv"
    payload = b"\x1aE\xdf\xa3" + b"0" * 12
    first.write_bytes(payload)
    second.write_bytes(payload)
    paths = (first.resolve(), second.resolve())
    frames = [FakeFrame(stamp) for stamp in (5000, 5040, 5100, 5200)]

    def open_container(reader: Any, **kwargs: Any) -> FakeContainer:
        if Path(reader.handle.name) not in paths:
            raise RuntimeError("unexpected fixture source")
        return FakeContainer(list(frames))

    old_native_av, old_image_av = native._load_av, images._load_av
    old_pillow = images.pillow_version
    native._load_av = lambda: SimpleNamespace(open=open_container)
    images._load_av = lambda: SimpleNamespace(__version__="frozen-av", library_versions={})
    images.pillow_version = "frozen-pillow"
    try:
        clips = tuple(NativeConcatClip(path, start=5, end=Fraction(26, 5)) for path in paths)
        scene_document = detect_native_concat_scenes(clips).to_dict()
        image_result = export_native_scene_images(first, root / "single-source")
        image_wire = (image_result.output_dir / "manifest.json").read_bytes()
    finally:
        native._load_av, images._load_av, images.pillow_version = (
            old_native_av,
            old_image_av,
            old_pillow,
        )

    # Assert we normalize a real v1 writer byte stream, not a reconstructed
    # semantic document with a different whitespace/key-order policy.
    parsed_image = json.loads(image_wire)
    assert image_wire == json.dumps(parsed_image, ensure_ascii=True, allow_nan=False, sort_keys=True).encode(
        "utf-8"
    )

    def normalized(value: Any) -> Any:
        if type(value) is str:
            result = value
            result = result.replace(scene_document["timeline_digest"], "<timeline-digest>")
            for index, path in enumerate(paths):
                result = result.replace(str(path), f"<source-{index}>")
                result = result.replace(path.as_posix(), f"<source-{index}>")
            return result
        if type(value) is list:
            return [normalized(item) for item in value]
        if type(value) is dict:
            return {key: normalized(item) for key, item in value.items()}
        return value

    return {
        "concat_scene_v1": json.dumps(
            normalized(scene_document),
            ensure_ascii=True,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8"),
        "single_source_image_v1": json.dumps(
            normalized(parsed_image), ensure_ascii=True, allow_nan=False, sort_keys=True
        ).encode("utf-8"),
    }


def digest_summary(root: Path) -> dict[str, dict[str, Any]]:
    return {
        name: {"bytes": len(wire), "sha256": hashlib.sha256(wire).hexdigest()}
        for name, wire in capture_v1_wire(root).items()
    }


if __name__ == "__main__":
    import sys
    from tempfile import TemporaryDirectory

    source_root = Path(sys.argv[1]).resolve()
    sys.path.insert(0, str(source_root / "src"))
    sys.path.insert(1, str(Path(__file__).resolve().parents[1]))
    with TemporaryDirectory(prefix="frame-v1-wire-") as directory:
        print(json.dumps(digest_summary(Path(directory)), sort_keys=True))
