"""Explainable key-frame selection for image sequences."""

from ._version import VERSION
from .benchmark import (
    BenchmarkConfig,
    BenchmarkProvenance,
    BenchmarkResult,
    BenchmarkRun,
    EvaluationMetrics,
    benchmark_manifest,
    evaluate_selection,
    render_benchmark_svg,
    run_benchmark,
    source_content_digest,
)
from .detectors import DetectorName, Transition, detect_transitions
from .editing import render_edl, render_scene_timecodes
from .exports import render_decision_csv, render_detection_csv, write_decision_csv
from .models import (
    AnimationConfig,
    ConcurrencyConfig,
    Frame,
    FrameDecision,
    FrameMetrics,
    ScanConfig,
    SelectionConfig,
    SelectionResult,
)
from .native_av import NativeAVSplitConfig
from .native_av_splitting import NativeAVSplitResult, split_native_av
from .native_histograms import (
    HistogramStatistic,
    NativeHistogramMeasurements,
    NativeHistogramReplayResult,
    NativeHistogramSample,
    analyze_native_histograms,
    capture_native_histograms,
    read_native_histograms,
    write_native_histogram_replay,
    write_native_histograms,
)
from .native_measurements import (
    NativeMeasurementLimits,
    NativeMeasurements,
    NativeReplayResult,
    analyze_native_measurements,
    capture_native_measurements,
    read_native_measurements,
    render_native_detection_csv,
    write_native_measurements,
    write_native_replay,
)
from .native_online import (
    NativeOnlineDiagnostics,
    NativeOnlineLimits,
    NativePixelChangeEnd,
    NativePixelChangeStream,
    NativePixelChangeUpdate,
    iter_native_pixel_change_jsonl,
    write_native_pixel_change_stream,
)
from .native_pixel_changes import (
    NativePixelChangeMeasurements,
    NativePixelChangeReplayResult,
    NativePixelChangeSample,
    PixelChangeDetectionConfig,
    PixelChangeStatistic,
    analyze_native_pixel_changes,
    capture_native_pixel_changes,
    read_native_pixel_changes,
    write_native_pixel_change_replay,
    write_native_pixel_changes,
)
from .native_scenes import (
    NativeDetectorStatistic,
    NativeScene,
    NativeSceneConfig,
    NativeSceneResult,
    NativeSceneSample,
    NativeSceneStatistic,
    detect_native_scenes,
)
from .native_splitting import (
    NativeClip,
    NativeSplitConfig,
    NativeSplitResult,
    native_scene_clips,
    split_native_video,
)
from .native_video import (
    NativeVideoConfig,
    NativeVideoDiagnostics,
    NativeVideoFrame,
    NativeVideoMetadata,
    NativeVideoStatus,
    NativeVideoStream,
)
from .otio_export import (
    OTIOCut,
    OTIOExportConfig,
    OTIOExportResult,
    OTIOMedia,
    otio_cuts_from_native,
    render_otio,
    write_otio_bundle,
)
from .pixel_changes import (
    PixelChange,
    PixelChangeConfig,
    PixelChangeLimits,
    PixelChangeWeights,
    measure_pixel_change,
)
from .pixel_histograms import (
    HistogramDetectionConfig,
    HistogramMode,
    PixelHistogram,
    PixelHistogramConfig,
    PixelHistogramLimits,
    histogram_distance,
    measure_pixel_histogram,
)
from .scanner import scan_frames
from .scene_detection import (
    DetectionConfig,
    DetectionResult,
    FrameStatistic,
    SceneDetectorName,
    detect_scenes,
)
from .scenes import SceneAnalysis, Shot, allocate_budget, analyze_scenes, detect_shots
from .selector import select_frames
from .timecode import FrameRate, FrameTimecode
from .video import VideoExtractionConfig, VideoExtractionResult, extract_video_frames, ffmpeg_available

__all__ = [
    "AnimationConfig",
    "BenchmarkConfig",
    "BenchmarkProvenance",
    "BenchmarkResult",
    "BenchmarkRun",
    "ConcurrencyConfig",
    "DetectionConfig",
    "DetectionResult",
    "DetectorName",
    "EvaluationMetrics",
    "Frame",
    "FrameDecision",
    "FrameMetrics",
    "FrameRate",
    "FrameStatistic",
    "FrameTimecode",
    "HistogramDetectionConfig",
    "HistogramMode",
    "HistogramStatistic",
    "NativeAVSplitConfig",
    "NativeAVSplitResult",
    "NativeClip",
    "NativeDetectorStatistic",
    "NativeHistogramMeasurements",
    "NativeHistogramReplayResult",
    "NativeHistogramSample",
    "NativeMeasurementLimits",
    "NativeMeasurements",
    "NativeOnlineDiagnostics",
    "NativeOnlineLimits",
    "NativePixelChangeEnd",
    "NativePixelChangeMeasurements",
    "NativePixelChangeReplayResult",
    "NativePixelChangeSample",
    "NativePixelChangeStream",
    "NativePixelChangeUpdate",
    "NativeReplayResult",
    "NativeScene",
    "NativeSceneConfig",
    "NativeSceneResult",
    "NativeSceneSample",
    "NativeSceneStatistic",
    "NativeSplitConfig",
    "NativeSplitResult",
    "NativeVideoConfig",
    "NativeVideoDiagnostics",
    "NativeVideoFrame",
    "NativeVideoMetadata",
    "NativeVideoStatus",
    "NativeVideoStream",
    "OTIOCut",
    "OTIOExportConfig",
    "OTIOExportResult",
    "OTIOMedia",
    "PixelChange",
    "PixelChangeConfig",
    "PixelChangeDetectionConfig",
    "PixelChangeLimits",
    "PixelChangeStatistic",
    "PixelChangeWeights",
    "PixelHistogram",
    "PixelHistogramConfig",
    "PixelHistogramLimits",
    "ScanConfig",
    "SceneAnalysis",
    "SceneDetectorName",
    "SelectionConfig",
    "SelectionResult",
    "Shot",
    "Transition",
    "VideoExtractionConfig",
    "VideoExtractionResult",
    "allocate_budget",
    "analyze_native_histograms",
    "analyze_native_measurements",
    "analyze_native_pixel_changes",
    "analyze_scenes",
    "benchmark_manifest",
    "capture_native_histograms",
    "capture_native_measurements",
    "capture_native_pixel_changes",
    "detect_native_scenes",
    "detect_scenes",
    "detect_shots",
    "detect_transitions",
    "evaluate_selection",
    "extract_video_frames",
    "ffmpeg_available",
    "histogram_distance",
    "iter_native_pixel_change_jsonl",
    "measure_pixel_change",
    "measure_pixel_histogram",
    "native_scene_clips",
    "otio_cuts_from_native",
    "read_native_histograms",
    "read_native_measurements",
    "read_native_pixel_changes",
    "render_benchmark_svg",
    "render_decision_csv",
    "render_detection_csv",
    "render_edl",
    "render_native_detection_csv",
    "render_otio",
    "render_scene_timecodes",
    "run_benchmark",
    "scan_frames",
    "select_frames",
    "source_content_digest",
    "split_native_av",
    "split_native_video",
    "write_decision_csv",
    "write_native_histogram_replay",
    "write_native_histograms",
    "write_native_measurements",
    "write_native_pixel_change_replay",
    "write_native_pixel_change_stream",
    "write_native_pixel_changes",
    "write_native_replay",
    "write_otio_bundle",
]

__version__ = VERSION
